version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - opentelemetry-collector
    ports:
      - "54040:54040"
      - "54041:54041"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "54039:54039"
    networks:
      - app-network

  loadgen:
    build:
      context: .
      dockerfile: ./loadgen/Dockerfile
    depends_on:
      - frontend
    networks:
      - app-network

  opentelemetry-collector:
    image: otel/opentelemetry-collector:latest
    environment:
      - ENVIRONMENT_ID=${ENVIRONMENT_ID}
      - DT_API_TOKEN=${DT_API_TOKEN}    
    container_name: opentelemetry-collector
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55680:55680"
    command: --config /etc/otel-collector-config.yaml      
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
