receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
  filter:
    metrics:
      exclude:
        match_type: regexp
        metric_names:
          - process.runtime.jvm.system.*

exporters:
  debug:
    verbosity: normal
  otlphttp:
    endpoint: https://${ENVIRONMENT_ID}.live.dynatrace.com/api/v2/otlp
    headers:
      Authorization: "Api-Token ${DT_API_TOKEN}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp]
    logs:
     receivers: [otlp]
     processors: [batch]
     exporters: [debug, otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch, filter]
      exporters: [debug, otlphttp]
  #telemetry:
  #  logs:
  #    level: debug" >/etc/otelcol/config.yaml